mysite/betting/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.conf import settings


from . import views, admin

app_name = 'betting'
urlpatterns = [
    url(r'^$', auth_views.login, name='login'),
	
	url(r'^logout/$', auth_views.logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),

	url(r'^index/$', views.index, name='index'),
	
	url(r'^signup/$', views.signup, name='signup'),
	
	url(r'^api/$', views.api, name='api'),
	
	url(r'^scores/$', views.scores, name='scores'),
    
]

mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^betting/', include('betting.urls')),
    url(r'^admin/', admin.site.urls),
]

mysite/betting/models.py
from django.db import models
from django.utils import timezone
import datetime
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class WeekNum(models.Model):
	week_num = models.IntegerField('Week Number', default=0)
	start_date = models.DateField('Week Starting', default=datetime.date(2017, 1, 1))
	is_current_week = models.BooleanField('Current Week?', default=False)
	def __str__(self):
		return str(self.week_num)

class Game(models.Model):
	game_text = models.CharField('Game Index', max_length=200, default='game')
	week = models.IntegerField('Week in Season', default = 0)
	home_team = models.CharField(max_length=200, default='')
	home_score = models.CharField(max_length=200, default='N/A')
	away_team = models.CharField(max_length=200, default='')
	away_score = models.CharField(max_length=200, default='N/A')
	favorite = models.CharField(max_length=200)
	line = models.FloatField(default=0)
	network = models.CharField(max_length=200)
	game_time = models.DateTimeField('game time/date', default=datetime.datetime(2017, 1, 1, 18, 00))
	game_of_week = models.BooleanField(default=False)
	def __str__(self):
		return "game"

class PossibleGame(models.Model):
	home = models.CharField(max_length=200)
	away = models.CharField(max_length=200)
	line = models.CharField(max_length=200)
	date = models.DateTimeField('game time/date', default=datetime.datetime(2017, 1, 1, 18, 00))
		
class Player(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
	score = models.IntegerField('Winston Cup Points', default=0)
	last_week_score = models.IntegerField('Last Week\'s Points', default=0)
	is_paid = models.BooleanField('Paid?', default=True)
	def __str__(self):
		return self.user.username

class SavedPick(models.Model):
	id = models.AutoField(primary_key=True)
	player = models.ForeignKey(Player, on_delete=models.CASCADE)
	week = models.IntegerField('Week in Season', default = 0)
	game_id = models.IntegerField('Game_ID', default=0)
	team = models.CharField('Team Name', max_length=200, default='')
	is_high_risk = models.BooleanField(default=False)
	def __str__(self):
		return 'saved pick'

class GameOfWeekScore(models.Model):
	player = models.ForeignKey(Player, on_delete=models.CASCADE)
	week = models.IntegerField(default=0)
	score = models.IntegerField('Game of Week Score', default=0)
	def __str__(self):
		return "Game of Week Score"
	
@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Player.objects.create(user=instance)
    instance.player.save()
		

mysite/betting/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'password1', 'password2', )
		

mysite/betting/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth.forms import UserCreationForm
import datetime, requests
from betting.forms import SignUpForm

from .models import Game, WeekNum, Player, SavedPick, GameOfWeekScore, PossibleGame


def login(request):
	if request.method == 'POST':
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(request, username=username, password=password)
		if user is not None:
			login(request, user)
			return redirect('index')
		else:
			return redirect('login')
	else:
		return redirect('login')
		
def signup(request):
	if request.method == 'POST':
		form = SignUpForm(request.POST)
		if form.is_valid():
			user = form.save()
			user.refresh_from_db()
			user.save()
			#username = form.cleaned_data.get('username')
			raw_password = form.cleaned_data.get('password1')
			user = authenticate(request, username=user.username, password=raw_password)
			auth_login(request, user)
			return redirect('/betting/index')

	else:
		form = SignUpForm()
	return render(request, 'betting/signup.html', {'form': form})
	
def index(request):
	current_week = WeekNum.objects.get(is_current_week=True)
	q = Game.objects.filter(game_of_week=True, week=current_week.week_num)
	if len(q) > 0:
		game_of_week = Game.objects.get(game_of_week=True, week=current_week.week_num)
	else:
		game_of_week = {}
	if request.method == 'POST':
		picks = request.POST
		high_risk_game_number = 0
		for game in picks:
			if game == "high_risk":
				high_risk_game_number = int(picks[game])
			if game == "game_of_week_score":
				print("trying to save game of week score...")
				q = GameOfWeekScore.objects.filter(week=current_week.week_num, player=request.user.player)
				q.delete()
				q = GameOfWeekScore(player=request.user.player, week=current_week.week_num, score=int(picks[game]))
				q.save()
				
		for i, game in enumerate(picks):
			if i != 0 and game != "high_risk" and game != "game_of_week_score":
				if high_risk_game_number != 0 and int(game) == high_risk_game_number:
					newpick = SavedPick(player=request.user.player, game_id=int(game), team=picks[game], is_high_risk=True, week=current_week.week_num)
				else:
					newpick = SavedPick(player=request.user.player, game_id=int(game), team=picks[game], week=current_week.week_num)
				q = SavedPick.objects.filter(game_id=int(game)).filter(player=request.user.player)
				if len(q) != 0:
					q.delete()
				newpick.save()
	game_list = Game.objects.filter(week=current_week.week_num)
	player_list = Player.objects.order_by('-score')
	saved_picks = SavedPick.objects.all().filter(player=request.user.player)
	context = {'game_list': game_list, 'current_week': current_week, 'player_list': player_list,  'saved_picks': saved_picks, 'game_of_week': game_of_week}
	return render(request, 'betting/index.html', context)
	
def scores(request):
	global u
	api = "https://cfb-scoreboard-api.herokuapp.com/v1/date/"
	week_list = {
			'8':  ['20171015', '20171016', '20171017', '20171018', '20171019', '20171020', '20171021'],
			'9':  ['20171022', '20171023', '20171024', '20171025', '20171026', '20171027', '20171028'],
			'10': ['20171029', '20171030', '20171031', '20171101', '20171102', '20171103', '20171104'],
			'11': ['20171105', '20171106', '20171107', '20171108', '20171109', '20171110', '20171111'],
			'12': ['20171112', '20171113', '20171114', '20171115', '20171116', '20171117', '20171118'],
			'13': ['20171119', '20171120', '20171121', '20171122', '20171123', '20171124', '20171125'],
			'14': ['20171126', '20171127', '20171128', '20171129', '20171130', '20171201', '20171202'],
			'15': ['20171203', '20171204', '20171205', '20171206', '20171207', '20171208', '20171209']
			}
	game_list = []
	pick_list = []	
	week, week_starting, current_user, gow_score = None, None, None, None
	if request.method == 'POST':
		input = request.POST
		if 'user_choice' in input:
			current_user = input['user_choice']
			players = Player.objects.all()
			for player in players:
				if player.user.username == current_user:
					u = player
			week = input['week_choice']
			week_starting = week_list[week][0]
			week_starting = week_starting[4:6] + '/' + week_starting[6:8] + '/' + week_starting[0:4]
		
			for date in week_list[week]:
				data = requests.get(api+date).json()
				for i in range(len(data['games'])):
					home = data['games'][i]['homeTeam']['displayName']
					try:
						game = Game.objects.get(home_team=home, week=int(week))
					except Game.DoesNotExist:
						game = None
					if game is not None:
						game.home_score = data['games'][i]['scores']['home']
						game.away_score = data['games'][i]['scores']['away']
						game.save()

			game_list = Game.objects.filter(week=int(week))
			pick_list = SavedPick.objects.filter(week=int(week), player=u)
			try:
				gow_score = GameOfWeekScore.objects.get(player=u, week=int(week))
			except GameOfWeekScore.DoesNotExist:
				gow_score = None
			
		if 'points' in input:
			p = int(input['points'])
			u.score += p
			u.last_week_score = p
			u.save()

	user_list = Player.objects.all()
	context = {'user_list': user_list, 'game_list': game_list, 'pick_list': pick_list, 'week': week, 'week_starting': week_starting, 'current_user': current_user, 'gow_score': gow_score}
	return render(request, 'betting/scores.html', context)
	
def api(request):
	global global_week
	api = "https://cfb-scoreboard-api.herokuapp.com/v1/date/"
	week_list = {
			'8':  ['20171015', '20171016', '20171017', '20171018', '20171019', '20171020', '20171021'],
			'9':  ['20171022', '20171023', '20171024', '20171025', '20171026', '20171027', '20171028'],
			'10': ['20171029', '20171030', '20171031', '20171101', '20171102', '20171103', '20171104'],
			'11': ['20171105', '20171106', '20171107', '20171108', '20171109', '20171110', '20171111'],
			'12': ['20171112', '20171113', '20171114', '20171115', '20171116', '20171117', '20171118'],
			'13': ['20171119', '20171120', '20171121', '20171122', '20171123', '20171124', '20171125'],
			'14': ['20171126', '20171127', '20171128', '20171129', '20171130', '20171201', '20171202'],
			'15': ['20171203', '20171204', '20171205', '20171206', '20171207', '20171208', '20171209']
			}
	
	if request.method == 'POST':
		input = request.POST
		if 'week_choice' in input:
			PossibleGame.objects.all().delete()
			week = input['week_choice']
			global_week = int(week)
			week_starting = week_list[week][0]
			week_starting = week_starting[4:6] + '/' + week_starting[6:8] + '/' + week_starting[0:4]
			for date in week_list[week]:
				data = requests.get(api+date).json()
				for i in range(len(data['games'])):
					home = data['games'][i]['homeTeam']['displayName']
					away = data['games'][i]['awayTeam']['displayName']
					line = data['games'][i]['odds']['spread']
					date = data['games'][i]['date']
					y = int(date[0:4])
					m = int(date[5:7])
					d = int(date[8:10])
					h = int(date[11:13])
					mm = int(date[14:16])
					date = datetime.datetime(y, m, d, h, mm)
					PossibleGame.objects.create(home=home, away=away, line=line, date=date)
			game_list = PossibleGame.objects.all()
			context = {'game_list': game_list, 'week': week, 'week_starting': week_starting }
			return render(request, 'betting/api.html', context)
		if 'game_choice' in input:
			q = Game.objects.filter(week=global_week)
			q.delete()
			game_of_week = input['game_of_week']
			game_choices = input.getlist("game_choice")
			for game in game_choices:
				print(game)
			for game in game_choices:
				is_game_of_week = False
				if game.startswith('manual'):
					id = game[6:len(game)]
					homeid = 'home' + id
					awayid = 'away' + id
					lineid = 'line' + id
					networkid = 'network' + id
					dateid = 'date' + id
					if game_of_week == 'gow' + id:
						is_game_of_week = True
					home = input[homeid]
					away = input[awayid]
					line = float(input[lineid])
					network = input[networkid]
					date = input[dateid]
					y = int(date[0:4])
					m = int(date[5:7])
					d = int(date[8:10])
					h = int(date[11:13])
					mm = int(date[14:16])
					date = datetime.datetime(y, m, d, h, mm)
					if line > 0:
						favorite = home
					else:
						favorite = away
					Game.objects.create(week=global_week, home_team=home, away_team=away, favorite=favorite, line=line, network=network, game_time=date, game_of_week=is_game_of_week)
				else:
					possible = PossibleGame.objects.get(id=int(game))
					lineid = game + "_line"
					networkid = game + "_network"
					home = possible.home
					away = possible.away
					line = float(input[lineid])
					network = input[networkid]
					if line > 0:
						favorite = home
					else:
						favorite = away
					date = possible.date
					if game_of_week == game:
						is_game_of_week = True
					Game.objects.create(week=global_week, home_team=home, away_team=away, favorite=favorite, line=line, network=network, game_time=date, game_of_week=is_game_of_week)					
	context = {}
	return render(request, 'betting/api.html', context)

mysite/betting/templates/betting/api.html
{% extends 'betting/base.html' %}
{% block title %}Load Games from API{% endblock %}

{% block content %}

<style>
table { border-collapse: collapse; }
td, th { 
	border 0.5px solid #cccccc;
	padding: 2px;	}
tr:nth-child(even) { background-color: #eeeeee }
</style>

<h3>List of Games</h3>
<p>Select a week then choose up to 15 games to add to the betting sheet, manually adding network and line info for
each selected game, as well as a selection for game of the week.  If away team is favored, the line should be negative.</p>

<form method="post" action="">
{% csrf_token %}

	<select name="week_choice">
		<option value="8">Week 8</option>
		<option value="9">Week 9</option>
		<option value="10">Week 10</option>
		<option value="11">Week 11</option>
		<option value="12">Week 12</option>
		<option value="13">Week 13</option>

	</select>
	<input type="submit">
</form>

{% if week %}
<h4>Week {{ week }} starting {{ week_starting }}</h4>

<form method="post" action="">
{% csrf_token %}

	<table>
		<tr>
			<th>Choose</th>
			<th>Home</th>
			<th>Away</th>
			<th>Pub Line</th>
			<th>Line</th>
			<th>Network</th>
			<th>Game Time</th>
			<th>Game of Week?</th>
		</tr>
		{% for g in game_list %}
		<tr>
			<td><center><input type="checkbox" name="game_choice" value="{{ g.id }}" id="{{ g.home }}"></center></td>
			<td><label for="{{ g.home }}">{{ g.home }}</label></td>
			<td>{{ g.away }}</td>
			<td>{{ g.line }}</td>
			<td><input type="text" name="{{ g.id }}_line" size=6></td>
			<td><input type="text" name="{{ g.id }}_network" size=15></td>
			<td>{{ g.date }}</td>
			<td><center><input type="radio" name="game_of_week" value="{{ g.id }}" required></center></td>
		</tr>			
		{% endfor %}
		{% for i in "123" %}
		<tr>
			<td><center><input type="checkbox" name="game_choice" value="manual{{ forloop.counter }}"></center></td>
			<td><input type="text" name="home{{ forloop.counter }}" size=30></td>
			<td><input type="text" name="away{{ forloop.counter }}" size=30></td>
			<td>N/A</td>
			<td><input type="text" name="line{{ forloop.counter }}" size=6></td>
			<td><input type="text" name="network{{ forloop.counter }}" size=15></td>
			<td><input type="datetime-local" name="date{{ forloop.counter }}"></td>
			<td><center><input type="radio" name="game_of_week" value="gow{{ forloop.counter }}"></center></td>
		</tr>
		{% endfor %}
	</table>
	<br><input type="submit" value="Submit Games">
	
</form>	
{% endif %}


{% endblock %}

mysite/betting/templates/betting/base.html
{% load static %}

<html>
	<head>
		<h1 style="font-family: arial black; background-color: #eeeeee; padding: 8px; box-shadow: 1px 2px 4px rgba(0, 0, 0, .5)">	<img src="{% static "betting/logo.jpg" %}" alt="logo" style="vertical-align: middle; box-shadow: 1px 2px 4px rgba(0, 0, 0, .5)">
The Better Betting Pool</h1>
		<p style="font-family: arial, sans-serif; line-height: 1.5">
		{% if user.is_authenticated %} Welcome, {{ user.first_name }} ({{ user.username }}) <a href="{% url 'betting:logout' %}">logout</a> {% if user.is_superuser %}<br><b>ADMIN:</b> <a href="{% url 'betting:index' %}">Betting sheet</a> / <a href="/admin">Django admin</a> / <a href="{% url 'betting:api' %}">API betting sheet</a> / <a href="{% url 'betting:scores' %}">Update player scores</a>{% endif %}
		{% else %} <a href="{% url 'betting:login' %}">login</a> / <a href="{% url 'betting:signup' %}">signup</a>{% endif %}
		</p>
		<hr>
		<title>
			{% block title %}Page Title{% endblock %}
		</title>
	
	</head>
	
	<body>
		
		{% block content %}
			Body content
		{% endblock %}
		
	</body>
	<br><hr>
</html>

mysite/betting/templates/betting/detail.html
<h1>{{ game.game_text }}</h1>
<ul>
{% for choice in game.choice_set.all %}
    <li>{{ team.team_text }}</li>
{% endfor %}
</ul>

mysite/betting/templates/betting/index - Copy.html
{% extends 'betting/base.html' %}
{% block title %}Index{% endblock %}

{% block content %}


<style>
table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
}

table.table1 { width: 100%; }
table.table2 { width: 100%; }

td, th {
    border: 1px solid #cccccc;
    text-align: left;
    padding: 8px;
}

th.th2 {font-family: times, serif; font-size: 18pt; font-style: bold}

td.td2 { border: 0px; width: 25%; vertical-align: top }

tr:nth-child(even) {
    background-color: #eeeeee;
}


</style>
<h3>Week # {{ current_week.week_num }} (Starting {{ current_week.start_date }})</h3>

{% if game_list %}

<form method="post" action="">
{% csrf_token %}

	<table class="table1">
		<tr>
			<th>Home Team</th>
			<th>Away Team</th>
			<th>Line</th>
			<th>Network</th>
			<th>Game Time</th>
			<th style="width: 85px">High Risk?</th>
			<th>Your Pick</th>
		</tr>
		
		{% for game in game_list %}

			<tr>
				<td><input type="radio" name="{{ game.id }}" id="choice{{ forloop.counter }}-1" value="{{ game.home_team }}" required>
				{% ifequal game.home_team game.favorite %}
					<label for="choice{{ forloop.counter }}-1"><b>{{ game.home_team }}</b></label>
				{% else %}
					<label for="choice{{ forloop.counter }}-1">{{ game.home_team }}</label>
				{% endifequal %} </td>
				<td><input type="radio" name="{{ game.id }}" id="choice{{ forloop.counter }}-2" value="{{ game.away_team }}">
				{% ifequal game.away_team game.favorite %}
					<label for="choice{{ forloop.counter }}-2"><b>{{ game.away_team }}</b></label>
				{% else %}
					<label for="choice{{ forloop.counter }}-2">{{ game.away_team }}</label>
				{% endifequal %}</td>
				<td>{{ game.line }}</td>
				<td>{{ game.network }}</td>
				<td>{{ game.game_time }}</td>
				<td><center><input type="radio" name="high_risk" value="{{ game.id }}" /></center></td>
				<td>
					{% for pick in saved_picks %}
						{% if pick.game_id == game.id %}
							{{ pick.team }}
							{% if pick.is_high_risk == True %}
								<b>(HR)</b>
							{% endif %}
						{% endif %}
					{% endfor %}
					
					
				</td>
			</tr>

		{% endfor %}

	</table>

<br>

<table class="table1" style="background-color: #eeeeee">
<td><b>Game of the Week: 
	{{game_of_week.home_team }} vs {{ game_of_week.away_team }} (Tie Breaker) Total Points Scored: 
	<input type="number" step="1" name="game_of_week_score" required />
</td>
</table>
<br>
* Favored team in <b>bold</b>
<br><br>
{% if user.player.is_paid %}<input type="submit" value="Save Your Picks" />
{% else %} <mark>Please pay up to save selections or see admin! <br>Thank you!</mark>
{% endif %}
</form>

{% else %}
<h2 style="background-color: #ffff00">No games selected yet!</h2>
{% endif %}

<br><hr>
<table class="table1" style="background-color: #eeeeee; padding: 8px; box-shadow: 1px 2px 4px rgba(0, 0, 0, .5);"><th class="th2"><center>Other Info</th></table>
<table class="table2">
	<tr>
		<td class="td2", style="width: 50%">
			<table class="table2">
				<caption><b>Winston Cup Standings</b></caption>
				<tr>
					<th style="width: 25%">Last Week's Points</th>
					<th style="width: 50%">User Info</th>
					<th style="width: 25%">Total Points</th>
				</tr>
				{% for player in player_list %}
				<tr>
					<td>{{ player.last_week_score }}</td>
					<td>{{ player.user.first_name }} {{ player.user.last_name }} ({{ player.user.username }})</td>
					<td>{{ player.score }}</td>
				</tr>
				{% endfor %}

			</table>
		</td>
		<td class="td2" style="border-right: 1px solid #cccccc">
			<center><b>Weekly Payout Rules</b>
			<center>$10 Cash with Entry
			<center>Entry deadline: Every Thursday at noon
			<center>All picks and payments go to Nathan Stamper
			<center>1st place 80% 2nd place 20%
			<hr>
			<center>2 Bonus points to winners of the Game of the Week
			<hr>
			<center><b>5 Point High Risk Game</b>
			<center>1 game per week, of your choice, can be selected as your high-risk game.  If you win the game, you will receive 5 additional Winston Cup points.  However, if you lose this game, 5 points will be deducted from your Winston Cup point total.  Note: Weekly participation in the High Risk Game is not mandatory.
		</td>
		<td class="td2" style="vertical-align: middle">
			<h3><center>Winston Cup Payout Formula</center></h3>
			<center>1st Place 70%</center>
			<center>2nd Place 20%</center>
			<center>Last Place 10%</center>
			<center>$25 Entry Fee</center>
			<center>Must declare prior entry of Week 2 Picks</center>
			<center>Cumulative Points</center>
		</td>
	</tr>
</table>
{% endblock %}

mysite/betting/templates/betting/index.html
{% extends 'betting/base.html' %}
{% block title %}The Better Betting Pool{% endblock %}

{% block content %}

<style>
table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
}

table.table1 { width: 100%; }
table.table2 { width: 100%; }

td, th {
    border: 1px solid #cccccc;
    text-align: left;
    padding: 8px;
}

th.th2 { padding: 6px;}

td.td2 { padding: 6px; }

tr:nth-child(even) {
    background-color: #eeeeee;
}
</style>

<h3 style="font-family: arial, sans-serif;">Week # {{ current_week.week_num }} (Starting {{ current_week.start_date }})</h3>

{% if game_list %}

<form method="post" action="">
{% csrf_token %}

	<table class="table1">
		<tr>
			<th>Home Team</th>
			<th>Away Team</th>
			<th>Line</th>
			<th>Network</th>
			<th>Game Time</th>
			<th style="width: 85px">High Risk?</th>
			<th>Your Pick</th>
		</tr>
		
		{% for game in game_list %}

			<tr>
				<td><input type="radio" name="{{ game.id }}" id="choice{{ forloop.counter }}-1" value="{{ game.home_team }}" required>
				{% ifequal game.home_team game.favorite %}
					<label for="choice{{ forloop.counter }}-1"><b>{{ game.home_team }}</b></label>
				{% else %}
					<label for="choice{{ forloop.counter }}-1">{{ game.home_team }}</label>
				{% endifequal %} </td>
				<td><input type="radio" name="{{ game.id }}" id="choice{{ forloop.counter }}-2" value="{{ game.away_team }}">
				{% ifequal game.away_team game.favorite %}
					<label for="choice{{ forloop.counter }}-2"><b>{{ game.away_team }}</b></label>
				{% else %}
					<label for="choice{{ forloop.counter }}-2">{{ game.away_team }}</label>
				{% endifequal %}</td>
				<td>{{ game.line }}</td>
				<td>{{ game.network }}</td>
				<td>{{ game.game_time }}</td>
				<td><center><input type="radio" name="high_risk" value="{{ game.id }}" /></center></td>
				<td>
					{% for pick in saved_picks %}
						{% if pick.game_id == game.id %}
							{{ pick.team }}
							{% if pick.is_high_risk == True %}
								<b>(HR)</b>
							{% endif %}
						{% endif %}
					{% endfor %}
					
					
				</td>
			</tr>

		{% endfor %}

	</table>

<br>
<div style="font-family: arial, sans-serif; background-color: #eeeeee; padding: 8px; border: 1px solid #cccccc;"><b>Game of the Week: 
	{{game_of_week.home_team }} vs {{ game_of_week.away_team }} (Tie Breaker) Total Points Scored: 
	<input type="number" step="1" name="game_of_week_score" required /></b>
</div>
<br>
<div style="font-family: arial, sans-serif;">* Favored team in <b>bold</b></div>
<br>
{% if user.player.is_paid %}<input type="submit" value="Save Your Picks" style="font-size: 16px;box-shadow: 1px 2px 4px rgba(0, 0, 0, .5);" />
{% else %} <mark>Please pay up to save selections or see admin! <br>Thank you!</mark>
{% endif %}
</form>

{% else %}
<h2 style="background-color: #ffff00">No games selected yet!</h2>
{% endif %}

<br><hr>
{% load static %}
<h2 style="font-family: arial black; background-color: #eeeeee; padding: 8px; box-shadow: 1px 2px 4px rgba(0, 0, 0, .5)">	<img src="{% static "betting/logo.jpg" %}" alt="logo" height="45px" width="117px" style="vertical-align: middle; box-shadow: 1px 2px 4px rgba(0, 0, 0, .5)">
Other Info</h2>
<fieldset style="border: 0px">
<div style="padding-right: 6px; width: 60%; float: left">
	<h3 style="font-family: arial, sans-serif; line-height: 4px"><center>Winston Cup Standings</center></h3>

	<table class="table2" style="box-shadow: 1px 2px 4px rgba(0, 0, 0, .5)">
		<tr>
			<th style="width: 20%; text-align: center">Last Week's Points</th>
			<th style="width: 60%">User Info</th>
			<th style="width: 20%; text-align: center">Total Points</th>
		</tr>
		{% for player in player_list %}
		<tr>
			<td><center>{{ player.last_week_score }}</center></td>
			<td>{{ player.user.first_name }} {{ player.user.last_name }} ({{ player.user.username }})</td>
			<td><center>{{ player.score }}</center></td>
		</tr>
		{% endfor %}

	</table>
</div>
<div style="border-left: 1px solid #cccccc; float: left; width: 37%; padding: 8px; font-family: arial, sans-serif;">
	<center><p style="line-height: 4px"><b>Winston Cup Payout Formula<br></b></p><p>1st Place 70% .. 2nd Place 20% .. Last Place 10% .. $25 Entry Fee .. Must declare prior entry of Week 2 Picks .. Cumulative weekly points</p>
	<hr>
	<p style="line-height: 4px"><br><b>Weekly Payout Rules<br></b></p><p>
	$10 Cash with Entry .. 	Entry deadline: Every Thursday at noon .. All picks and payments go to Nathan Stamper .. 1st place 80% 2nd place 20%</p>
	<hr>
	<p><b>2 Bonus points</b> to winners of the Game of the Week</p>
	<hr>
	<p style="line-height: 4px"><br><b>5-Point High-Risk Game<br></b></p><p>
	1 game per week, of your choice, can be selected as your high-risk game.  If you win the game, you will receive 5 additional Winston Cup points.  However, if you lose this game, 5 points will be deducted from your Winston Cup point total.  Note: Weekly participation in the High Risk Game is not mandatory.</p>
	</center>
</div>
</fieldset>

{% endblock %}

mysite/betting/templates/betting/login.html
{% extends 'betting/base.html' %}
{% block title %}Login{% endblock %}

{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>



{% endblock %}